---
# install influxdb
- hosts: pi
  become: yes

  vars:
    download_url: "https://dl.influxdata.com/influxdb/releases/influxdb-1.3.6_linux_amd64.tar.gz"
    workdir:  "/home/riemann"


  tasks: 
    - get_url:  
       url :  "{{download_url}}"
       dest:  "{{workdir}}"
  
  